// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as $$Map from "bs-platform/lib/es6/map.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

var compare = Caml_obj.caml_compare;

var IconMap = $$Map.Make(/* module */[/* compare */compare]);

export {
  IconMap ,
  
}
/* IconMap Not a pure module */
