// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE

import * as Block from "bsb-native/lib/es6/block.js";
import * as Curry from "bsb-native/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "/home/tomis/Documents/Git/reasontest/node_modules/reason-react/src/ReasonReact.js";
import * as Button$ReactTemplate from "./Button.bs.js";
import * as ReactJsComponentGen from "./ReactJsComponent.gen";

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* show */1];
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, ReactJsComponentGen.make(false, /* array */[])), match ? self[/* state */1][/* greeting */2] : null, React.createElement("input", {
                              value: self[/* state */1][/* greeting */2],
                              onChange: (function ($$event) {
                                  return Curry._1(self[/* send */3], /* InputChange */[$$event.target.value]);
                                })
                            }), ReasonReact.element(undefined, undefined, Button$ReactTemplate.make(undefined, undefined, undefined, /* help */-989121855, undefined, /* array */["Help Button"])), ReasonReact.element(undefined, undefined, Button$ReactTemplate.make((function (_event) {
                                    return Curry._1(self[/* send */3], /* Toggle */1);
                                  }), undefined, undefined, /* warning */164354652, /* warning */164354652, /* array */["Warning Button"])), ReasonReact.element(undefined, undefined, Button$ReactTemplate.make((function (_event) {
                                    return Curry._1(self[/* send */3], /* Toggle */1);
                                  }), true, undefined, /* success */944645571, /* success */944645571, /* array */["Success Button"])), ReasonReact.element(undefined, undefined, Button$ReactTemplate.make(undefined, undefined, undefined, /* danger */512905955, /* danger */512905955, /* array */["Danger Button"])));
            }),
          /* initialState */(function (param) {
              return /* record */[
                      /* count */4,
                      /* show */true,
                      /* greeting */""
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* record */[
                              /* count */state[/* count */0],
                              /* show */!state[/* show */1],
                              /* greeting */state[/* greeting */2]
                            ]]);
                } else {
                  return /* Update */Block.__(0, [/* record */[
                              /* count */state[/* count */0] + 1 | 0,
                              /* show */state[/* show */1],
                              /* greeting */state[/* greeting */2]
                            ]]);
                }
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* count */state[/* count */0],
                            /* show */state[/* show */1],
                            /* greeting */action[0]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  make ,
  
}
/* component Not a pure module */
