// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as ApolloLinks from "reason-apollo/src/ApolloLinks.bs.js";
import * as ReasonApollo from "reason-apollo/src/ReasonApollo.bs.js";
import * as ApolloInMemoryCache from "reason-apollo/src/ApolloInMemoryCache.bs.js";

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(undefined, undefined, /* () */0);

var httpLink = ApolloLinks.createHttpLink("https://api.digitransit.fi/routing/v1/routers/hsl/index/graphql", undefined, undefined, undefined, undefined, undefined, /* () */0);

var instance = ReasonApollo.createApolloClient(httpLink, inMemoryCache, undefined, undefined, undefined, undefined, /* () */0);

export {
  inMemoryCache ,
  httpLink ,
  instance ,
  
}
/* inMemoryCache Not a pure module */
