// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Icons$ReactTemplate from "./config/Icons.bs.js";

var component = ReasonReact.statelessComponent("Icon");

function svg(disabled, bsSize) {
  return Css.style(/* :: */[
              Css.width(Css.px(20)),
              /* :: */[
                Css.height(Css.px(20)),
                /* :: */[
                  Css.position(Css.relative),
                  /* :: */[
                    Css.display(Css.inlineBlock),
                    /* :: */[
                      Css.marginBottom(Css.zero),
                      /* :: */[
                        Css.textAlign(Css.center),
                        /* :: */[
                          Css.verticalAlign(Css.textTop),
                          /* :: */[
                            Css.whiteSpace(Css.nowrap),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Styles = /* module */[/* svg */svg];

function make(iconType, $staropt$star, $staropt$star$1, _children) {
  var disabled = $staropt$star !== undefined ? $staropt$star : false;
  var bsSize = $staropt$star$1 !== undefined ? $staropt$star$1 : /* normal */812216871;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return React.createElement("svg", {
                          className: svg(disabled, bsSize),
                          viewBox: "0 0 1024 1024",
                          xmlns: "http://www.w3.org/2000/svg"
                        }, React.createElement("path", {
                              d: Icons$ReactTemplate.getIconPath(iconType)
                            }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  Styles ,
  make ,
  
}
/* component Not a pure module */
