// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Icons$ReactTemplate from "./config/Icons.bs.js";

var component = ReasonReact.statelessComponent("Icon");

function button(disabled, bsStyle) {
  return Css.style(/* :: */[
              Css.position(Css.relative),
              /* :: */[
                Css.display(Css.inlineBlock),
                /* :: */[
                  Css.boxShadow(undefined, Css.px(1), undefined, undefined, true, Css.rgba(255, 255, 255, 0.1)),
                  /* :: */[
                    Css.borderWidth(Css.px(1)),
                    /* :: */[
                      Css.marginBottom(Css.zero),
                      /* :: */[
                        Css.borderColor(Css.green),
                        /* :: */[
                          Css.borderBottomColor(Css.red),
                          /* :: */[
                            Css.textAlign(Css.center),
                            /* :: */[
                              Css.verticalAlign(Css.middle),
                              /* :: */[
                                Css.cursor(disabled ? /* notAllowed */939907157 : /* pointer */-786317123),
                                /* :: */[
                                  Css.backgroundImage(Css.none),
                                  /* :: */[
                                    Css.borderStyle(Css.solid),
                                    /* :: */[
                                      Css.whiteSpace(Css.nowrap),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Styles = /* module */[/* button */button];

function make(iconType, onClick, $staropt$star, $staropt$star$1, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return React.createElement("svg", {
                          viewBox: "0 0 1024 1024",
                          xmlns: "http://www.w3.org/2000/svg"
                        }, React.createElement("path", {
                              d: Icons$ReactTemplate.getIconPath(iconType)
                            }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  component ,
  Styles ,
  make ,
  
}
/* component Not a pure module */
