// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "/home/tomis/Documents/Git/reasontest/node_modules/reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "/home/tomis/Documents/Git/reasontest/node_modules/reason-react/src/ReasonReact.js";
import * as App$ReactTemplate from "./App.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App$ReactTemplate.make(/* array */[])), "app");

export {
  
}
/*  Not a pure module */
