// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE

import * as ReactJsComponentGen from "./ReactJsComponent.gen";

function make(prim, prim$1) {
  return ReactJsComponentGen.make(prim, prim$1);
}

export {
  make ,
  
}
/* ./ReactJsComponent.gen Not a pure module */
