// Generated by BUCKLESCRIPT VERSION 4.0.7000, PLEASE EDIT WITH CARE


function getColor(color) {
  if (color !== -618203037) {
    if (color >= 317324542) {
      if (color >= 317325434) {
        return /* `hex */[
                5194459,
                "f0f0f0"
              ];
      } else {
        return /* `hex */[
                5194459,
                "777777"
              ];
      }
    } else if (color !== 58474434) {
      return /* `hex */[
              5194459,
              "212121"
            ];
    } else {
      return /* `hex */[
              5194459,
              "004400"
            ];
    }
  } else {
    return /* `hex */[
            5194459,
            "ffffff"
          ];
  }
}

export {
  getColor ,
  
}
/* No side effect */
